repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
      - id: gitleaks
- repo: local
  hooks:
  - id: rubocop
    name: rubocop
    entry: bundle install
    always_run: true
    pass_filenames: false
    language: system
